import {Router} from "express";
import {auth} from "../auth.js";
import * as operations from "../controllers/admin.js";
export const adminApiRoutes=Router();
adminApiRoutes.use(auth);
adminApiRoutes.get("/me",(req,res)=>res.json(req.user));
adminApiRoutes.get("/products",async(req,res)=>res.json(await operations.adminProducts(req)));
adminApiRoutes.get("/providers",async(req,res)=>res.json(await operations.adminDeliveryProviders(req)));
adminApiRoutes.put("/providers/:provider",async(req,res)=>res.status(200).json(await operations.saveAdminDeliveryProvider(req)));
adminApiRoutes.post("/providers/:provider/test",async(req,res)=>res.status(200).json(await operations.testAdminDeliveryProvider(req)));

adminApiRoutes.get("/orders",async(req,res)=>res.status(200).json(await operations.adminOrders(req)));
adminApiRoutes.get("/orders/:id",async(req,res)=>res.status(200).json(await operations.adminOrder(req)));
adminApiRoutes.patch("/orders/:id/status",async(req,res)=>res.status(200).json(await operations.setOrderStatus(req)));
adminApiRoutes.post("/orders/:id/delivery/quote",async(req,res)=>res.status(200).json(await operations.deliveryQuote(req)));
adminApiRoutes.post("/orders/:id/delivery",async(req,res)=>res.status(200).json(await operations.dispatchDelivery(req)));
adminApiRoutes.post("/orders/:id/delivery/simulate",async(req,res)=>res.status(200).json(await operations.simulateDelivery(req)));
adminApiRoutes.post("/orders/:id/delivery/sync",async(req,res)=>res.json(await operations.syncDelivery(req)));
adminApiRoutes.get("/orders/:id/delivery/qr",async(req,res)=>res.set("Cache-Control","no-store").type("png").send(await operations.pickupQr(req)));
adminApiRoutes.post("/products",async(req,res)=>res.status(201).json(await operations.createProduct(req)));
adminApiRoutes.patch("/products/:id",async(req,res)=>res.status(200).json(await operations.updateProduct(req)));
adminApiRoutes.delete("/products/:id",async(req,res)=>res.status(200).json(await operations.deleteProduct(req)));
