ALTER TABLE customers ADD COLUMN IF NOT EXISTS phone VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS delivery_address VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS delivery_notes VARCHAR(500) NOT NULL DEFAULT '';
