ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS legal_name VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS tax_id VARCHAR(24) NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS legal_address VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS legal_email VARCHAR(190) NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS legal_registration VARCHAR(255) NOT NULL DEFAULT '';